apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-service
  name: web-service
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webtest
  type: NodePort
status:
  loadBalancer: {}
