apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webtest
  name: webtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webtest
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
