apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webtest
  name: webtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webtest
    spec:
      containers:
      - image: mmumshad/simple-webapp-color
        name: httpd
        resources: {}
status: {}
